### ISSUE TITLE
crash server side

### ISSUE THREAD

**Issue by celittle3** [Konlii/OrganicCreepers#5]
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.flashoverride.organiccreepers.handlers.EventHandler.explosionEvent(EventHandler.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1687_EventHandler_explosionEvent_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:568)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:409)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.func_73660_a(TileInfusionMatrix.java:277)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.flashoverride.organiccreepers.handlers.EventHandler.explosionEvent(EventHandler.java:37)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1687_EventHandler_explosionEvent_Detonate.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:568)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1169)
	at net.minecraft.world.World.func_72876_a(World.java:2300)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.craftCycle(TileInfusionMatrix.java:409)
	at thaumcraft.common.tiles.crafting.TileInfusionMatrix.func_73660_a(TileInfusionMatrix.java:277)

-- Block entity being ticked --
Details:
	Name: thaumcraft:tileinfusionmatrix // thaumcraft.common.tiles.crafting.TileInfusionMatrix
	Block type: ID #2158 (tile.infusion_matrix // thaumcraft.common.blocks.crafting.BlockInfusionMatrix // thaumcraft:infusion_matrix)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-210,149,490), Chunk: (at 14,9,10 in -14,30; contains blocks -224,0,480 to -209,255,495), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2158 (tile.infusion_matrix // thaumcraft.common.blocks.crafting.BlockInfusionMatrix // thaumcraft:infusion_matrix)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Unexplored
	All players: 1 total; [EntityPlayerMP['Jess_The_Lily'/777, l='Unexplored', x=-215.89, y=147.00, z=491.23]]
	Chunk stats: ServerChunkCache: 871 Drop: 0
	Level seed: 5496094115214410642
	Level generator: ID 07 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-9,68,250), Chunk: (at 7,4,10 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 199379391 game time, 200747777 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 70571 (now: false), thunder time: 12670 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2

**Comment by Konlii** [comment]
What version of Organic Creepers are you using?  This looks a lot like an issue that was already fixed in v1.2.3.  And when I say "looks a lot like" I mean "that's the exact line number as the issue that was fixed, but in the latest version of the mod, that code is on a different line."

So please retry with the latest version (v1.2.4) and definitely let me know if you still have issues because that would mean that I didn't fix it after all.

**Comment by celittle3** [comment]
ok thank you, testing the 1.2.4 version now.
